console.time('time taken by code')
console.log('hey world')
console.log('hey')
console.log(14)
console.log(12+2)
console.log(12*2)
console.log(23/2)
console.warn('this is a warning')
console.log(true);
console.log({shobhnik:'this',marks:90})
console.table({shobhnik:'this',marks:90})
console.timeEnd('time taken by code')
